import assert from 'node:assert/strict';
import {listDay,listInstant,routineDue,checkedToday,checkId,reminderCandidates} from '../list-schedule.js';
import {scheduleListReminders,listReminderWanted} from '../worker/src/list-reminders.js';
import {notificationKindEnabled} from '../notification-policy.js';
const day='2026-10-09',at=listInstant(day,'15:00');
assert.equal(at,Date.parse('2026-10-09T19:00Z'));
assert.equal(listInstant('2026-12-09','15:00'),Date.parse('2026-12-09T20:00Z'));
assert.equal(listInstant('2026-03-08','02:30'),0);
assert.equal(listInstant('2026-02-30','12:00'),0);
assert.equal(listDay(Date.parse('2026-10-10T03:59Z')),day);
assert.equal(listDay(Date.parse('2026-10-10T04:00Z')),'2026-10-10');
const item={id:'routine',title:'feed the cat',type:'task',done:false,routineDays:[5,6],reminderTime:'15:00',reminderOffsets:[60,30,0],reminderTo:'both',createdAt:at-7200000};
assert.ok(routineDue(item,day));assert.equal(routineDue(item,'2026-10-11'),false);
const checks=[{id:checkId(item.id,day),done:true}];
assert.ok(checkedToday(item,checks,day));assert.equal(checkedToday(item,checks,'2026-10-10'),false);
assert.deepEqual(reminderCandidates(item,at-3600000).map(p=>p.offset),[60]);
assert.deepEqual(reminderCandidates({...item,createdAt:at-1800000},at-1800000).map(p=>p.offset),[30]);
assert.equal(reminderCandidates({...item,done:true},at).length,0);
assert.equal(reminderCandidates({...item,reminderOffsets:[]},at).length,0);
assert.equal(reminderCandidates({...item,reminderTime:'00:30',routineDays:[6]},Date.parse('2026-10-10T03:30Z'))[0].day,'2026-10-10');
const documents=new Map(),household='households/demo';documents.set(household+'/items/routine',item);
const db={list:async()=>[item],get:async path=>documents.get(path),createMany:async rows=>{if(rows.some(row=>documents.has(row.path)))return false;rows.forEach(row=>documents.set(row.path,row.fields));return true;}};
await scheduleListReminders(db,household,at-3600000);const count=documents.size;
await scheduleListReminders(db,household,at-3600000);assert.equal(documents.size,count,'retry cannot duplicate');
const pings=[...documents].filter(([path])=>path.includes('/outbox/')).map(([,value])=>value);
assert.deepEqual(pings.map(p=>p.to).sort(),['her','him']);
const savedNow=Date.now;Date.now=()=>at-3600000;
try {
 assert.ok(await listReminderWanted(db,household,pings[0]));
 documents.set(household+'/routineChecks/'+checkId(item.id,day),{done:true});
 assert.equal(await listReminderWanted(db,household,pings[0]),false);
 await scheduleListReminders(db,household,at-1800000);assert.equal(documents.size,count+1,'completed routine queues nothing else');
 documents.delete(household+'/routineChecks/'+checkId(item.id,day));
 documents.set(household+'/items/routine',{...item,reminderTime:'16:00'});
 assert.equal(await listReminderWanted(db,household,pings[0]),false,'edited time cancels queued ping');
 documents.delete(household+'/items/routine');assert.equal(await listReminderWanted(db,household,pings[0]),false);
}finally{Date.now=savedNow;}
assert.equal(notificationKindEnabled('list-reminder',{categories:{asks:false}}),false);
assert.equal(notificationKindEnabled('list-nudge',{categories:{asks:false}}),false);
console.log('ROUTINES: weekdays, midnight, DST, independent checks, offsets, midnight heads-up, idempotent pings, completion, deletion, edits and preferences pass');
