import assert from 'node:assert/strict';
import {weeklyReport} from '../weekly-report.js';
import {leagueWeek} from '../league-scores.js';
const day='2026-10-09',now=Date.parse(day+'T18:00Z');
const w=(person,attempts=1,date=day)=>({day:date,person,done:true,won:true,attempts,updatedAt:now});
const t=(person,type,count,total=10,date=day)=>({day:date,type,person,count,total,done:true,complete:count===total,startedAt:now-120000,finishedAt:now,closesAt:now+3600000});
const words=[w('her'),w('him',2)],timed=[t('her','search',10),t('her','crossword',3,6),t('him','search',6),t('him','crossword',6,6)];
let report=weeklyReport(day,words,timed,null,now);
assert.deepEqual(report.totals,{her:175,him:120});assert.deepEqual(report.totals,leagueWeek(day,words,timed,now).scores);
assert.equal(report.stats.her.crossword.points,25);assert.equal(report.winner,null);
assert.deepEqual(report.highlights.her.sources.map(g=>g.id),['word']);
assert.deepEqual(report.highlights.her.best.map(g=>g.id),['word','search']);
const final={week:'2026-10-05',round:0,format:'trio',scoreVersion:2,scores:{her:175,him:120},winners:['her'],settledAt:now};
report=weeklyReport(day,words,timed,final,now+86400000);
assert.equal(report.winner,'her');assert.equal(report.edge[0].id,'word');assert.equal(report.edge[0].margin,60);assert.equal(report.complete,true);
assert.equal(weeklyReport(day,[...words,words[0]],timed,null,now).totals.her,175,'duplicate snapshots cannot award points twice');
const tie='2026-10-05-tie-1',partial={...t('him','search',5,10,tie),done:false,finishedAt:null,startedAt:now-1000};
const closed={...final,round:1,tieRound:1,scores:{her:375,him:120}};
report=weeklyReport(day,[...words,w('her',1,tie)],[...timed,partial],closed,now+86400000);
assert.equal(report.stats.him.search.points,30,'a timer expiring after an early clinch cannot change the archived result');
assert.equal(report.totals.her,375);assert.ok(report.complete);assert.equal(report.entries.at(-1).tie,1);
report=weeklyReport(day,[...words,w('her',1,tie)],[...timed,t('her','search',10,10,tie)],{...closed,scores:{her:475,him:120}},now);
assert.equal(report.stats.her.search.points,150,'first-week tie games count even though the week ID predates the timed-game launch');assert.ok(report.complete);
assert.equal(weeklyReport(day,[...words,w('her',1,'2026-10-05-tie-2')],timed,final,now).stats.her.word.points,100,'unawarded later ties excluded');
report=weeklyReport(day,[],[],final,now);assert.equal(report.complete,false);assert.equal(report.edge,null,'missing history must not invent a winning reason');
assert.deepEqual(report.totals,final.scores);
const empty=weeklyReport(day,[],[],null,now);assert.deepEqual(empty.totals,{her:0,him:0});assert.equal(empty.highlights.her.best.length,0);
const lost=weeklyReport(day,[{...w('her',5),won:false}],[t('her','search',0)],null,now);assert.equal(lost.totals.her,0);assert.equal(lost.stats.her.search.finished,1);
assert.equal(weeklyReport(day,[{...w('her',2),won:false,done:false}],[],null,now+86400000).entries.find(e=>e.day===day).games[0].people.her.detail,'unfinished · closed');
assert.equal(weeklyReport('2026-10-11',[w('her',1,'2026-10-11')],[t('her','search',10,10,'2026-10-11')],null,now).totals.her,300);
console.log('WEEKLY REPORT: per-game/day sums, double points, partials, missing history, duplicate snapshots, tie carry and frozen early-clinch recaps pass');
