import assert from 'node:assert/strict';
import {wordFinish} from '../word-celebration.js';
import {coronationCandidate} from '../word-coronation.js';
const game=(tries,won=true)=>({done:true,won,guesses:Array(tries).fill('apple')});
assert.equal(wordFinish({done:false}),null);
assert.equal(wordFinish(game(1)).tier,'jackpot');
assert.equal(wordFinish(game(2)).tier,'brilliant');
for(const n of [3,4,5])assert.equal(wordFinish(game(n)).tier,'win');
assert.equal(wordFinish(game(5,false)).text,'you did your best :c');
assert.ok(wordFinish(game(1)).pieces>wordFinish(game(2)).pieces);
const now=Date.parse('2026-10-19T14:00Z');
const week={week:'2026-10-12',settledAt:now-1000,scores:{her:40,him:30},winners:['her']};
assert.equal(coronationCandidate([],now),null);
assert.equal(coronationCandidate([{...week,winners:[]}],now),null);
assert.equal(coronationCandidate([{...week,winners:['her','him']}],now),null);
assert.equal(coronationCandidate([{...week,settledAt:now-8*86400000}],now),null);
assert.equal(coronationCandidate([{...week,settledAt:now+1}],now),null);
assert.equal(coronationCandidate([{...week,settledAt:undefined}],now),null);
const winner=coronationCandidate([week,{...week,week:'2026-10-05'}],now);
assert.equal(winner.winner,'her');assert.equal(winner.streak,2);
assert.equal(coronationCandidate([week,{...week,week:'2026-10-05',settledAt:now}],now).week,'2026-10-12','late old ties cannot replace the latest champion');
console.log('WORD CELEBRATIONS: attempt tiers, no unfinished celebrations, settled-only crowns, stale history and streaks pass');
