import { createDataLayer } from './firebase-data.js';
import { setupAuthUI, applyViewerTheme, escapeHtml, setButtonBusy, showFailure, toast } from './ui-helpers.js';
import { personName } from './profile-store.js';

const params=new URLSearchParams(location.search);const viewer=params.get('as')==='him'?'him':'her';const other=viewer==='her'?'him':'her';const $=id=>document.getElementById(id);let ideas=[];let vibe='go out';let data;
applyViewerTheme(viewer);document.querySelector('.back-to-side').href=`${viewer}.html`;
data=await createDataLayer({collectionName:'dates',onItems(items){ideas=items.sort((a,b)=>(Number(b.favorite)-Number(a.favorite))||((b.createdAt||0)-(a.createdAt||0)));render();},onAuth(user){setupAuthUI(data,user);}});if(data.mode==='local')setupAuthUI(data,{local:true});

document.querySelectorAll('.date-vibe').forEach(button=>button.addEventListener('click',()=>{vibe=button.dataset.vibe;document.querySelectorAll('.date-vibe').forEach(item=>item.classList.toggle('active',item===button));}));
$('date-form').addEventListener('submit',async event=>{event.preventDefault();const title=$('date-title').value.trim();const note=$('date-note').value.trim();const button=$('date-submit');setButtonBusy(button,true,'saving…');try{await data.add({title,note,vibe,addedBy:viewer,favorite:false,createdAt:Date.now()});void data.push(other,{title:'new date idea ✦',body:title,sound:'twinkle.wav',channelId:'our-twinkles',priority:'high',data:{kind:'date',from:viewer,url:`dates.html?as=${other}`}}).catch(()=>{});event.target.reset();toast('saved for later ✦');}catch(_){showFailure('the idea escaped.','check the internet and save it again.');}finally{setButtonBusy(button,false);}});
$('pick-random').addEventListener('click',event=>{if(!ideas.length){$('random-date').textContent='we need at least one idea first.';return;}event.currentTarget.classList.remove('is-picking');void event.currentTarget.offsetWidth;event.currentTarget.classList.add('is-picking');const idea=ideas[Math.floor(Math.random()*ideas.length)];$('random-date').innerHTML=`<strong>${escapeHtml(idea.title)}</strong>${idea.note?`<span>${escapeHtml(idea.note)}</span>`:''}`;});
$('date-list').addEventListener('click',async event=>{const button=event.target.closest('[data-action]');if(!button)return;const idea=ideas.find(item=>item.id===button.closest('[data-id]')?.dataset.id);if(!idea)return;button.disabled=true;try{if(button.dataset.action==='favorite')await data.update(idea.id,{favorite:!idea.favorite});else if(button.dataset.action==='delete')await data.remove(idea.id);}catch(_){showFailure('that edit did not stick.','check the internet and tap it again.');button.disabled=false;}});

function render(){$('date-count').textContent=`${ideas.length} saved`;$('date-empty').hidden=ideas.length>0;$('date-list').innerHTML=ideas.map(idea=>`<article class="date-idea-card${idea.favorite?' favorite':''}" data-id="${escapeHtml(idea.id)}"><div class="date-idea-top"><span>${escapeHtml(idea.vibe||'idea')}</span><div class="date-actions"><button data-action="favorite" aria-label="${idea.favorite?'Unfavorite':'Favorite'}">${idea.favorite?'★':'☆'}</button><button data-action="delete" aria-label="Delete">×</button></div></div><h3>${escapeHtml(idea.title)}</h3>${idea.note?`<p>${escapeHtml(idea.note)}</p>`:''}<small>added by ${escapeHtml(personName(idea.addedBy))}</small></article>`).join('');}
window.addEventListener('littlelist:profile',render);
