// One tiny prompt a day. The multiplier visits all 100 without repeats until
// the whole set has had a turn, and both phones choose the same one offline.
export const QUESTIONS = [
  'What snack would fix today a little?',
  'What is one thing you want to do this weekend?',
  'Which song has been stuck in your head?',
  'What small thing made you laugh lately?',
  'What should we cook together next?',
  'What place would you like to wander around?',
  'What is your ideal lazy morning?',
  'What is a tiny thing you are proud of?',
  'What should we watch when we have no brain cells left?',
  'What food are you craving right now?',
  'What should we put on our grocery list?',
  'What is one thing you want help with?',
  'What is a date idea under $20?',
  'Which animal are you spiritually today?',
  'What is a photo we should take together?',
  'What is a place you want to revisit?',
  'What would make this week easier?',
  'What is your current comfort show?',
  'What is a weirdly good smell?',
  'Which chore would you delete forever?',
  'What is something you want to learn?',
  'What is your favorite way to do nothing?',
  'What is one thing we should celebrate?',
  'What is a very specific dream dinner?',
  'What is a small purchase you keep thinking about?',
  'What would be a fun rainy-day plan?',
  'What are you looking forward to this month?',
  'What is your best recent discovery?',
  'What could use a tiny upgrade at home?',
  'Where should we go for a walk?',
  'What is a movie you would rewatch with me?',
  'What would your perfect breakfast be?',
  'What is a thing you want to make together?',
  'What is a silly name for our next plant?',
  'What is your favorite time of day lately?',
  'What is a game we should play again?',
  'Which dessert should we hunt down?',
  'What is one thing you wish people knew about your day?',
  'What is a tiny win from today?',
  'What would make a good low-effort date?',
  'What is a place you are curious about?',
  'What is the best thing you ate this week?',
  'What is something you want us to try once?',
  'What sound feels like home?',
  'What is a hobby you would try if supplies were free?',
  'Which errand could become a date?',
  'What is your go-to bad-day meal?',
  'What is a small thing I do that helps?',
  'What is a small thing I could do more often?',
  'What is a song you want me to hear?',
  'What should we do on our next day off?',
  'What is your current oddly specific obsession?',
  'What is a memory you want to keep?',
  'What is a place you would take a visitor?',
  'What is a simple way to make tonight nicer?',
  'What is a question you wish I asked more?',
  'What is something funny we should remember?',
  'What is a snack you would defend in court?',
  'What is a good name for a tiny imaginary shop?',
  'What is the best weather for a walk?',
  'What is your most useful little habit?',
  'What is a thing you want to stop putting off?',
  'What is one thing we can make easier for future us?',
  'Which aisle always traps you at the store?',
  'What is a book you want to talk about?',
  'What is a movie scene you still think about?',
  'What is your ideal picnic food?',
  'What should our next kitchen experiment be?',
  'What is a place you would like to see at night?',
  'What is a tiny adventure we can do nearby?',
  'What has been surprisingly nice lately?',
  'What is one thing you need a break from?',
  'What would you put in a care package for me?',
  'What is your favorite way to be cheered up?',
  'What is a date we could do at home?',
  'What should we order if neither of us cooks?',
  'What is a thing you wish had a pause button?',
  'What is a place that feels calm to you?',
  'What is the most unserious thing you learned?',
  'What is a compliment you secretly love?',
  'What would be a fun new tradition?',
  'What is a tiny task we can knock out together?',
  'What would our ideal Sunday include?',
  'What is a scent that reminds you of childhood?',
  'What is something you would happily do twice?',
  'What is a picture we should print?',
  'What is your dream late-night snack?',
  'What is one thing you want to tell me in person?',
  'Which part of today deserves a redo?',
  'What is your favorite corner of our city?',
  'What is an opinion you have about breakfast?',
  'What is something we should put on the calendar?',
  'What is a harmless hill you will die on?',
  'What is one thing you hope goes well tomorrow?',
  'What is a good song for our next drive?',
  'What would make errands less boring?',
  'What is a little thing that feels like us?',
  'What should we do with an unexpected free hour?',
  'What is a new place you want to eat at?',
  'What is one thing you are glad we did?'
];

export function questionForDay(day) {
  const date = Date.parse(`${day}T00:00:00Z`);
  if (!Number.isFinite(date)) throw new Error('invalid question day');
  const promptId = ((Math.floor(date / 86400000) * 37 + 11) % QUESTIONS.length + QUESTIONS.length) % QUESTIONS.length;
  return { promptId, prompt: QUESTIONS[promptId] };
}
